name: FirstWorkFlow

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    

jobs:
  FirstJob:
    name: running a bash command
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Generate an output that would be used in next step
        id: UNK_USER
        run: echo "USER=MANUAL_BOT" >> "$GITHUB_OUTPUT"
        
      - name: run a bash command
        run: |
          pwd
          echo "Username is ${GITHUB_ACTOR} on ${{ runner.os }} by ${{ steps.UNK_USER.outputs.USER }}"

      - name: adding job summary
        run: echo "Build at BUILD_TIME=$(date +'%T')" >> $GITHUB_STEP_SUMMARY
        
      - run: echo 'Successful :medal_sports:' >> $GITHUB_STEP_SUMMARY
  
